libinstall.setStep("Copying computercraft programs")
fs.copy("/rom/programs", "/bin/ccUnchanged")
fs.delete("/bin/ccUnchanged/cd")
fs.delete("/bin/ccUnchanged/copy")
fs.delete("/bin/ccUnchanged/delete")
fs.delete("/bin/ccUnchanged/edit")
fs.delete("/bin/ccUnchanged/exit")
fs.delete("/bin/ccUnchanged/lua")
libinstall.setProgress(6)
fs.delete("/bin/ccUnchanged/mkdir")
fs.delete("/bin/ccUnchanged/move")
fs.delete("/bin/ccUnchanged/rename")
fs.delete("/bin/ccUnchanged/shell")
fs.delete("/bin/ccUnchanged/reboot")
fs.delete("/bin/ccUnchanged/shutdown")
libinstall.setProgress(7)