libinstall.setStep("Setting system branch")
fs.makeDir("/etc/zpm")
local repo = fs.open("/etc/zpm/sysbranch", "w")
repo.write(_branch)
repo.close()

function Download(path)
	libinstall.setStep("Downloading "..branch..path.."...")
	data = http.get("https://raw.githubusercontent.com/Zac13422/zOS/"..branch..path)
	data = data.readAll()
	local file = fs.open(path, "w")
	file.write(data)
	file.close()
     
end
 


      
Download("/.settings")
Download("/startup")
libinstall.setProgress(8)
Download("/api/text")
Download("/api/system")
libinstall.setProgress(9)
Download("/api/user")
Download("/bin/cd")
libinstall.setProgress(10)
Download("/bin/cp")
Download("/bin/date")
libinstall.setProgress(11)
Download("/bin/edit")
Download("/boot/login")
libinstall.setProgress(12)
Download("/bin/logout")
Download("/bin/lua")
libinstall.setProgress(13)
Download("/bin/mkdir")
Download("/bin/mv")
libinstall.setProgress(14)
Download("/bin/passwd")
Download("/bin/pwd")
libinstall.setProgress(15)
Download("/bin/reboot")
Download("/bin/rename")
Download("/bin/rm")
libinstall.setProgress(16)
Download("/bin/shutdown")
Download("/bin/zpm")  
Download("/bin/zsh")
Download("/bin/useradd")
libinstall.setProgress(17)